services:

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy

  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    env_file:
      - .env
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    networks:
      - backend
    depends_on:
      - postgres

  courses:
    build:
      context: .
      dockerfile: courses/Dockerfile
    env_file:
      - .env
    ports:
      - "${COURSES_PORT}:${COURSES_PORT}"
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - ./users/init.sql:/docker-entrypoint-initdb.d/1-users.sql:ro
      - ./courses/init.sql:/docker-entrypoint-initdb.d/1-courses.sql:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

  redis_sk:
    image: redis:alpine
    ports:
      - "${REDIS_SK_PORT}:${REDIS_PORT}"
    networks:
      - backend
    command:
      - redis-server
      - "--requirepass"
      - "${REDIS_SK_PASSWORD}"
      - "--loglevel warning"

  redis_rl:
    image: redis:alpine
    ports:
      - "${REDIS_RL_PORT}:${REDIS_PORT}"
    networks:
      - backend
    command:
      - redis-server
      - "--requirepass"
      - "${REDIS_RL_PASSWORD}"
      - "--loglevel warning"

  prometheus:
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    networks:
      - monitoring
    command:
      - "--log.level=error"

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      - GF_LOG_LEVEL=error
      - GL_SECURITY_ADMIN_PASSWORD="${GRAFANA_PASSWORD}"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
  backend:
    driver: bridge
volumes:
  grafana-data:
